# docker-compose.yml
services:
  web:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - FILE_STORAGE_PATH=${FILE_STORAGE_PATH:-/workspace}
    working_dir: /app
    depends_on:
      - terminal

  terminal:
    build: .
    volumes:
      - .:/app
    stdin_open: true
    tty: true