version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - terminal

  terminal:
    build:
      context: .
      dockerfile: Dockerfile.terminal
    volumes:
      - ${FILE_STORAGE_PATH:-./workspace}:/workspace
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
    command: ["tail", "-f", "/dev/null"]