# Dockerfile.terminal
FROM ubuntu:latest

# Install necessary packages
RUN apt-get update && apt-get install -y tmux

# Set a long-running command to keep the container active
CMD ["tmux", "new-session", "-d", "-s", "timelord", "tail", "-f", "/dev/null"]
