version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - terminal

  terminal:
    build:
      context: .
      dockerfile: Dockerfile.terminal
    volumes:
      - ${FILE_STORAGE_PATH:-./workspace}:/workspace
    container_name: timelord-terminal
    tty: true
    stdin_open: true
    environment:
      - NODE_ENV=development
    command: sh -c "tmux new-session -d -s timelord; while true; do sleep 3600; done"
